[package]
name = "mpi"
version = "0.1.0"
authors = ["Benedikt Steinbusch <benedikt.steinbusch@googlemail.com>"]
description = "Message Passing Interface bindings for Rust"

homepage = "https://github.com/bsteinb/rsmpi"
repository = "https://github.com/bsteinb/rsmpi"

readme = "README.md"

keywords = [ "message-passing", "distributed memory", "parallel" ]

license = "MIT"

build = "build.rs"

[dependencies]
libc = "0.1.8"

[build-dependencies]
gcc = "0.3.8"

[build-dependencies.bindgen]
git = "https://github.com/crabtw/rust-bindgen.git"

[build-dependencies.probe-c-api]
git = "https://github.com/quantheory/probe-c-api.git"

#[dependencies.c_import]
#git = "https://github.com/vojtechkral/rust-c-import.git"
